# Spring properties
spring:
  application:
     name: clientes-service  # Service registers under this name
  hibernate:
     ddl-auto: none
  datasource:
     url: jdbc:mysql://localhost:3306/gt-clientes
     username: grantienda
     password: grantienda


# Discovery Server Access
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 15000   # HTTP (Tomcat) port
